export const APP_ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  userManagement: '/user-management',
  teamManagement: '/team-management',
  assignment: '/assignment',
  assignmentTeamDetails: '/assignment/team',
  report: '/report',
  teamDailyReport: '/team-management/daily-report',
  teamWorkMark: '/team-management/work-mark',
  teamDashboard: '/team-management/dashboard',
  remoteBidManagement: '/remote-job/bid-management',
  remoteCallManagement: '/remote-job/call-management',
  remoteDashboard: '/remote-job/dashboard',
  remoteProfileManagement: '/remote-job/profile-management',
} as const