# Generated by Django 5.2 for assignments-service.

import uuid
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('deadline', models.DateField()),
                ('objective', models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])),
                ('progress', models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['deadline', 'team_name', 'task_name'],
            },
        ),
    ]
